// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm57mnNMIm4zPOlDe6oG7atC_crxss4yM',
    appId: '1:427628788483:android:d3fbf9cba7d4e53b564736',
    messagingSenderId: '427628788483',
    projectId: 'albanote-renewal',
    storageBucket: 'albanote-renewal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0spADbfmdohqM94sz0U8V5MZgN8VdP0o',
    appId: '1:427628788483:ios:6b4be84354a54ebe564736',
    messagingSenderId: '427628788483',
    projectId: 'albanote-renewal',
    storageBucket: 'albanote-renewal.appspot.com',
    iosClientId: '427628788483-u2723bg0q6vkevti8529n466kagq3ef0.apps.googleusercontent.com',
    iosBundleId: 'com.blac2013.albanoteProject',
  );
}
