// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAodln_un5VuyiNV5KcYUbJUIQpGN43lZI',
    appId: '1:823612286899:android:892f332c1fc239cb0b4dc6',
    messagingSenderId: '823612286899',
    projectId: 'newalbanote',
    storageBucket: 'newalbanote.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxF3prpDbWtcTt7lgkTqkIWYzKAvpui50',
    appId: '1:823612286899:ios:9c69e9ec9d3906940b4dc6',
    messagingSenderId: '823612286899',
    projectId: 'newalbanote',
    storageBucket: 'newalbanote.appspot.com',
    androidClientId: '823612286899-jpsgr1o5bjdp9780bsfq2091vikf143v.apps.googleusercontent.com',
    iosClientId: '823612286899-dkjghc09s26e3ob1sc8fiaf2o7442j5a.apps.googleusercontent.com',
    iosBundleId: 'com.blac2013.albanoteProject',
  );
}
